// Auto-derived from the SF Symbols catalog (public/sfsymbols-catalog.json).
// Each unique category tag and how many symbols carry it.
export const SFSYMBOL_CATEGORIES: { name: string; count: number }[] = [
  { name: "Multicolor", count: 2231 },
  { name: "Draw", count: 2017 },
  { name: "Objects & Tools", count: 1470 },
  { name: "Variable", count: 1097 },
  { name: "Automotive", count: 828 },
  { name: "Human", count: 636 },
  { name: "Devices", count: 617 },
  { name: "Arrows", count: 599 },
  { name: "Indices", count: 582 },
  { name: "Commerce", count: 559 },
  { name: "Home", count: 504 },
  { name: "Fitness", count: 368 },
  { name: "Nature", count: 314 },
  { name: "Gaming", count: 229 },
  { name: "Communication", count: 222 },
  { name: "Camera & Photos", count: 207 },
  { name: "Weather", count: 171 },
  { name: "Privacy & Security", count: 162 },
  { name: "Editing", count: 149 },
  { name: "Maps", count: 136 },
  { name: "Accessibility", count: 125 },
  { name: "Health", count: 121 },
  { name: "Transportation", count: 117 },
  { name: "Media", count: 104 },
  { name: "Connectivity", count: 95 },
  { name: "Text Formatting", count: 83 },
  { name: "Math", count: 78 },
  { name: "Keyboard", count: 76 },
  { name: "Shapes", count: 55 },
  { name: "Time", count: 46 },
];
